/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;
import ec.edu.ups.controlador.ControladorCliente;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author ASUS
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCrearCliente crearCliente;
    private  ControladorCliente controladorCliente;
    private Locale Localizacion;
    private  ResourceBundle mensajes;
    
    public VentanaPrincipal() {
        initComponents();
        controladorCliente = new ControladorCliente();
        //System.out.println("Localizacion por defecto:"+Locale.getDefault().getLanguage());
        Localizacion=new Locale("es", "EC");
        Locale.setDefault(Localizacion);
        cambiarIdioma();
       // System.out.println(" Localizacion forzada: "+Locale.getDefault().getLanguage());
       /* mensajes=ResourseBundle.getBundle("ec.edu.ups.idiomas.mensajes",Locale.getDefault().getLanguage());
        System.out.println("Mensajes");
        System.out.println(mensajes.getString("menu.item.crear"));*/
    }
public  void cambiarIdioma(){
    mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes",Locale.getDefault());
    clienteMenu.setText(mensajes.getString("menu cliente"));
    productoMenu.setText(mensajes.getString("menu.producto"));
    
    
}
    
    /**
     * Creates new form NewMDIApplication
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        clienteMenu = new javax.swing.JMenu();
        itemcrearmenu = new javax.swing.JMenuItem();
        buscamenu = new javax.swing.JMenuItem();
        actualizaMenu = new javax.swing.JMenuItem();
        eliminaMenu = new javax.swing.JMenuItem();
        ListaMenu = new javax.swing.JMenuItem();
        productoMenu = new javax.swing.JMenu();
        itemcrearmenu1 = new javax.swing.JMenuItem();
        buscamenu2 = new javax.swing.JMenuItem();
        actualizaMenu2 = new javax.swing.JMenuItem();
        eliminaMenu2 = new javax.swing.JMenuItem();
        ListaMenu2 = new javax.swing.JMenuItem();
        fileMenu4 = new javax.swing.JMenu();
        itemcrearmenu2 = new javax.swing.JMenuItem();
        buscamenu3 = new javax.swing.JMenuItem();
        actualizaMenu3 = new javax.swing.JMenuItem();
        eliminaMenu3 = new javax.swing.JMenuItem();
        ListaMenu3 = new javax.swing.JMenuItem();
        fileMenu3 = new javax.swing.JMenu();
        itemespañol = new javax.swing.JMenuItem();
        itemingles = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu1.setText("jMenu1");

        jMenuItem5.setText("jMenuItem5");

        jMenu2.setText("jMenu2");
        jMenu2.setInheritsPopupMenu(true);

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienteMenu.setMnemonic('f');
        clienteMenu.setText("Cliente");

        itemcrearmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemcrearmenu.setMnemonic('o');
        itemcrearmenu.setText("Crear");
        itemcrearmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcrearmenuActionPerformed(evt);
            }
        });
        clienteMenu.add(itemcrearmenu);

        buscamenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        buscamenu.setMnemonic('s');
        buscamenu.setText("Buscar");
        buscamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscamenuActionPerformed(evt);
            }
        });
        clienteMenu.add(buscamenu);

        actualizaMenu.setMnemonic('a');
        actualizaMenu.setText("Actualizar");
        actualizaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaMenuActionPerformed(evt);
            }
        });
        clienteMenu.add(actualizaMenu);

        eliminaMenu.setMnemonic('x');
        eliminaMenu.setText("Eliminar");
        eliminaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaMenuActionPerformed(evt);
            }
        });
        clienteMenu.add(eliminaMenu);

        ListaMenu.setText("Listar");
        ListaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMenuActionPerformed(evt);
            }
        });
        clienteMenu.add(ListaMenu);

        menuBar.add(clienteMenu);

        productoMenu.setMnemonic('f');
        productoMenu.setText("Producto");

        itemcrearmenu1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        itemcrearmenu1.setMnemonic('o');
        itemcrearmenu1.setText("Crear Producto");
        itemcrearmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcrearmenu1ActionPerformed(evt);
            }
        });
        productoMenu.add(itemcrearmenu1);

        buscamenu2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        buscamenu2.setMnemonic('s');
        buscamenu2.setText("Buscar Producto");
        buscamenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscamenu2ActionPerformed(evt);
            }
        });
        productoMenu.add(buscamenu2);

        actualizaMenu2.setMnemonic('a');
        actualizaMenu2.setText("Actualizar  Producto");
        actualizaMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaMenu2ActionPerformed(evt);
            }
        });
        productoMenu.add(actualizaMenu2);

        eliminaMenu2.setMnemonic('x');
        eliminaMenu2.setText("Eliminar Producto");
        eliminaMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaMenu2ActionPerformed(evt);
            }
        });
        productoMenu.add(eliminaMenu2);

        ListaMenu2.setText("Listar Producto");
        ListaMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMenu2ActionPerformed(evt);
            }
        });
        productoMenu.add(ListaMenu2);

        menuBar.add(productoMenu);

        fileMenu4.setMnemonic('f');
        fileMenu4.setText("Factura");

        itemcrearmenu2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemcrearmenu2.setMnemonic('o');
        itemcrearmenu2.setText("Crear Factura");
        itemcrearmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcrearmenu2ActionPerformed(evt);
            }
        });
        fileMenu4.add(itemcrearmenu2);

        buscamenu3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        buscamenu3.setMnemonic('s');
        buscamenu3.setText("Buscar Factura");
        buscamenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscamenu3ActionPerformed(evt);
            }
        });
        fileMenu4.add(buscamenu3);

        actualizaMenu3.setMnemonic('a');
        actualizaMenu3.setText("Actualizar Factura");
        actualizaMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaMenu3ActionPerformed(evt);
            }
        });
        fileMenu4.add(actualizaMenu3);

        eliminaMenu3.setMnemonic('x');
        eliminaMenu3.setText("Eliminar Factura");
        eliminaMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaMenu3ActionPerformed(evt);
            }
        });
        fileMenu4.add(eliminaMenu3);

        ListaMenu3.setText("Listar Factura");
        ListaMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaMenu3ActionPerformed(evt);
            }
        });
        fileMenu4.add(ListaMenu3);

        menuBar.add(fileMenu4);

        fileMenu3.setMnemonic('f');
        fileMenu3.setText("Idioma");

        itemespañol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        itemespañol.setMnemonic('s');
        itemespañol.setText("Español");
        itemespañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemespañolActionPerformed(evt);
            }
        });
        fileMenu3.add(itemespañol);

        itemingles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        itemingles.setMnemonic('a');
        itemingles.setText("Ingles");
        itemingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteminglesActionPerformed(evt);
            }
        });
        fileMenu3.add(itemingles);

        menuBar.add(fileMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaMenuActionPerformed
            // System.exit(0);
           VentanaEliminarCliente ventanaEliminarcClente= new VentanaEliminarCliente(controladorCliente);
        ventanaEliminarcClente.setVisible(true);
        desktopPane.add(ventanaEliminarcClente);
        
        
    }//GEN-LAST:event_eliminaMenuActionPerformed

    private void itemcrearmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcrearmenuActionPerformed
        // TODO add your handling code here:
          if(crearCliente == null || !crearCliente.isVisible()){
            crearCliente = new VentanaCrearCliente(controladorCliente);
            crearCliente.setVisible(true);
            desktopPane.add(crearCliente);
        }        
    }//GEN-LAST:event_itemcrearmenuActionPerformed

    private void buscamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscamenuActionPerformed
        // TODO add your handling code here:
        VentanaBuscarCliente buscarCliente=new VentanaBuscarCliente(controladorCliente);
        buscarCliente.setVisible(true);
        desktopPane.add(buscarCliente);
    }//GEN-LAST:event_buscamenuActionPerformed

    private void actualizaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaMenuActionPerformed
        // TODO add your handling code here:
       VentanaActualizarCliente ventanaActualizarCliente=new VentanaActualizarCliente(controladorCliente);
       ventanaActualizarCliente.setVisible(true);
       desktopPane.add(ventanaActualizarCliente);
        
    }//GEN-LAST:event_actualizaMenuActionPerformed

    private void ListaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMenuActionPerformed
        // TODO add your handling code here:

        VentanaListarCliente ventanaListarClientene=new VentanaListarCliente(controladorCliente);
        ventanaListarClientene.setVisible(true);
        desktopPane.add(ventanaListarClientene);
    }//GEN-LAST:event_ListaMenuActionPerformed

    private void itemcrearmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcrearmenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcrearmenu1ActionPerformed

    private void buscamenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscamenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscamenu2ActionPerformed

    private void actualizaMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizaMenu2ActionPerformed

    private void eliminaMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminaMenu2ActionPerformed

    private void ListaMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaMenu2ActionPerformed

    private void iteminglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteminglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iteminglesActionPerformed

    private void itemespañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemespañolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemespañolActionPerformed

    private void itemcrearmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcrearmenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemcrearmenu2ActionPerformed

    private void buscamenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscamenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscamenu3ActionPerformed

    private void actualizaMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizaMenu3ActionPerformed

    private void eliminaMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminaMenu3ActionPerformed

    private void ListaMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ListaMenu;
    private javax.swing.JMenuItem ListaMenu2;
    private javax.swing.JMenuItem ListaMenu3;
    private javax.swing.JMenuItem actualizaMenu;
    private javax.swing.JMenuItem actualizaMenu2;
    private javax.swing.JMenuItem actualizaMenu3;
    private javax.swing.JMenuItem buscamenu;
    private javax.swing.JMenuItem buscamenu2;
    private javax.swing.JMenuItem buscamenu3;
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem eliminaMenu;
    private javax.swing.JMenuItem eliminaMenu2;
    private javax.swing.JMenuItem eliminaMenu3;
    private javax.swing.JMenu fileMenu3;
    private javax.swing.JMenu fileMenu4;
    private javax.swing.JMenuItem itemcrearmenu;
    private javax.swing.JMenuItem itemcrearmenu1;
    private javax.swing.JMenuItem itemcrearmenu2;
    private javax.swing.JMenuItem itemespañol;
    private javax.swing.JMenuItem itemingles;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu productoMenu;
    // End of variables declaration//GEN-END:variables

}
